config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'à propos', to: 'pages#about', as: 'about'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'terms', to: 'pages#terms', as: 'terms'
    # autres routes...

  # Defines the root path route ("/")
  # root "posts#index"

  resources :professionals do
    resources :appointments, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
  end


  resources :users, only: [:show, :edit, :destroy] do
    member do
      get 'professionals', to: 'professionals#pro_index', as: :pro_index
      get 'professionals/:professional_id', to: 'professionals#pro_show', as: :pro_show
    end

    member do
      resources :pets
    end
  end

  resources :animals, only: [:index, :show]

  resources :pricings, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :professional, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :orders

  validates :first_name, :last_name, :photo, presence: true
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @appointments = Appointment.where(user_id: @user.id)
    @pets = Pet.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.first_name = user_params[:first_name]
    @user.last_name = user_params[:last_name]
    @user.photo.attach(user_params[:photo])
    if @user.update!
      redirect_to user_path(@user)
    else
      render new, alert: "Erreur lors de la modification de votre profil"
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo)
  end

end

app/views/users/show.html.erb
<div>
  <div>
    <div class="p-4 text-center">
      <div class="row">
        <%# my profil %>
        <div class="col card_pro p-4 m-2 text-center" style="width: 47%;">
          <h2> <strong> Mon Profil </strong> </h2>
          <%= cl_image_tag @user.photo.key, width: 100, style: "border-radius: 50%; margin: 20px; aspect-ratio: 1;", class:"object-fit-cover" %>
          <p>Nom : <strong> <%=@user.first_name%> </strong></p>
          <p>Prénom : <strong> <%=@user.last_name%> </strong></p>
          <p>Email : <strong> <%=@user.email%> </strong></p>
          <div>
            <%= link_to "Modifier mon profil", edit_user_registration_path(current_user), class: "btn btn-primary my-4" %>
          </div>
        </div>
        <%# my pets %>
        <div class="col card_pro p-4 m-2 text-center" style="width: 47%;">
          <div class="d-flex flex-row justify-content-center">
            <h2 class="mx-3"> <strong> Mes animaux </strong> </h2>
            <a href="<%=new_pet_path(current_user)%>" class="btn btn-primary rounded-circle shadow object-fit-cover" >
              <i class="fa-solid fa-plus"></i>
            </a>
          </div>


          <% if @pets.empty? %>
            <p class="mt-3">Vous n'avez pas d'animaux</p>
            <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734435780/dog-thinking-about-bone-removebg-preview_nlayll.png" alt="pas d'animaux" style="width: 200px; ">
          <% else %>
            <div class="d-flex flex-row justify-content-center" >
              <% @pets.each do |pet| %>
                <a href="<%=pet_path(current_user, pet)%>" class="text-decoration-none">
                  <%= cl_image_tag pet.photo.key, width: 150, style: "border-radius: 50%; margin: 20px; aspect-ratio: 1;", class:"shadow"%>
                </a>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%# my appointments %>
    <div class="row card_pro p-4 mx-3 text-center">
      <h2 class="mb-3"> <strong> Mes rendez-vous </strong> </h2>
      <% if @appointments.empty? %>
        <div class="text-center">
          <p >Vous n'avez pas de rendez-vous</p>
          <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1733845850/owner-playing-with-pet-dog_vfnehl.png" alt="pas de rdv" style="width: 200px;" >
        </div>
      <% else %>
        <% @appointments.each do |a| %>
          <div class="col-lg-4 col-md-12 col-12">
            <a href="<%=professional_appointment_path(a.professional, a)%>" style="text-decoration: none; color: black;">
              <div class="card_pro p-4 m-1 text-start" style="background-color: #f7e6d4;">
                <div class="text-end">
                  <div >
                    <p><%= a.date.strftime("%d/%m/%Y")%></p>
                    <p><%= a.start_time.strftime("%H:%M")%></p>
                  </div>
                </div>
                <p>Professionnel : <strong><%= a.professional.name %></strong></p>
                <p style="word-wrap: break-word; word-break: break-word;">Motif de la visite : <%= truncate(a.reason, length: 100, omission: '...') %></p>
              </div>
            </a>
          </div>
        <% end %>
      <% end%>
    </div>
  </div>
</div>