config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'à propos', to: 'pages#about', as: 'about'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'terms', to: 'pages#terms', as: 'terms'
    # autres routes...

  # Defines the root path route ("/")
  # root "posts#index"

  resources :professionals do
    resources :appointments, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
  end


  resources :users, only: [:show, :edit, :destroy] do
    member do
      get 'professionals', to: 'professionals#pro_index', as: :pro_index
      get 'professionals/:professional_id', to: 'professionals#pro_show', as: :pro_show
    end

    member do
      resources :pets
    end
  end

  resources :animals, only: [:index, :show]

  resources :pricings, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end


end

app/views/shared/_all_service.html.erb
<div class="d-flex flex-column shadow"  style="width: 300px; height: 100vh; background-color:rgba(236, 230, 230, 0.31); padding: 20px">
  <div class="text-center m-4">
    <h3> Mes Services </h3>
  </div>
  <% @professionals.each do |professional| %>
    <a href="<%= pro_show_user_path(current_user, professional) %>" class="btn btn-outline-info m-1 text-black rounded rounded-4 <%= 'btn-primary' if professional == selected_professional %>">
      <%= professional.specialty %>
    </a>
  <% end %>
</div>

app/views/shared/_all_slot.html.erb
<%= turbo_frame_tag :all_slot do %>
  <div>
    <% start_hour = 8 # Heure de début
        end_hour = 17  # Heure de fin
        interval = 60  # Durée entre les créneaux en minutes
      %>
    <% current_time = Time.parse("#{selected_date} #{start_hour}:00") %>
    <% end_time = Time.parse("#{selected_date} #{end_hour}:00") %>
    <div data-appointment-target="times">
      <% while current_time <= end_time do %>
        <%@appointment = Appointment.find_by(start_time: current_time, professional: professional)%>
        <% if (@appointment.nil?) %>
          <%= link_to current_time.strftime("%H:%M"), pro_show_user_path(current_user, professional,date: @selected_date, appointment: nil),
              class:"btn btn-outline-primary m-2",
              data: {time: current_time.strftime("%H:%M")}%>
        <% else %>
          <%= link_to current_time.strftime("%H:%M"), pro_show_user_path(current_user, professional,date: @selected_date, appointment: @appointment),
              class:"btn btn-outline-primary m-2 btn-info text-dark",
              data: {time: current_time.strftime("%H:%M"),
                    turbo: false}%>
        <% end %>
        <% current_time += interval.minutes %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_all_slot_not_selected.html.erb
<%= turbo_frame_tag :all_slot do %>

  <%# all appointment slot %>
  <div>
    <% start_hour = 8 # Heure de début
        end_hour = 17  # Heure de fin
        interval = 60  # Durée entre les créneaux en minutes
      %>
    <% current_time = Time.parse("#{start_hour}:00") %>
    <% end_time = Time.parse("#{end_hour}:00") %>
    <div data-appointment-target="times">
      <% while current_time <= end_time do %>
        <a href="#" class="btn btn-outline-primary m-2" data-time="<%= current_time.strftime("%H:%M") %>" data-action="click->appointment#select">
          <%= current_time.strftime("%H:%M") %>
        </a>
        <% current_time += interval.minutes %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_appointment_details.html.erb
<%= turbo_frame_tag :appointment_details do %>
  <h5 class="text-start m-4"> <strong>Détail du rendez-vous : </strong> </h5>
  <% @appointment = Appointment.find(appointment) %>
  <div class="card_pro d-flex flex-row justify-content-between">
    <div>
      <div class="d-flex flex-row">
        <p>Nom : </p>
        <h5 class="mx-2"> <strong><%= @appointment.user.first_name%> <%= @appointment.user.last_name%></strong></h5>
      </div>
      <div class="d-flex flex-row my-1 mt-4">
        <p>Animal concerné : </p>
        <p class="mx-2"> <%= Pet.find(@appointment.pet_id).name%> </p>
      </div>
      <div class="d-flex flex-row my-1">
        <p>Type : </p>
        <p class="mx-2"> <%= Pet.find(@appointment.pet_id).species%> </p>
      </div>
      <div class="d-flex flex-row my-1">
        <p>Motif du rendez-vous : </p>
        <p class="mx-2"> <%= @appointment.reason%> </p>
      </div>
    </div>
    <div>
      <%= cl_image_tag Pet.find(@appointment.pet_id).photo.key,  style:"width: 100px; aspect-ratio:1; border-radius: 20px" %>
    </div>
  </div>
<% end %>

app/views/shared/_available_slots.html.erb
<div class="m-2">
  <h4>Prochains rendez-vous disponibles</h4>
  <% 7.times do |i| %>

    <% date = (DateTime.current.to_date + i).strftime('%d-%m-%Y')%>

    <div class="nav-item dropdown" data-controller="appointment-selected", data-appointment-selected-api-key-value=<%=professional.id%>>
      <a href="#" class="btn btn-outline-primary w-100 m-1" data-appointment-selected-target="selectedDate">

        <%# get all the appointments for this professional %>
        <%= date %>
        <% @appointments = Appointment.where(professional: professional, date: Time.parse(date))%>

        <%# get all the appointment times for this professional %>
        <% @appointment_times = [] %>
        <% @appointments.each do |appointment| %>
          <% @appointment_times << appointment.start_time.strftime("%H:%M") %>
        <% end%>
      </a>

      <%# show all available slot for appointment %>
      <div class="d-none d-flex justify-content-center mx-2" data-appointment-selected-target="times" style="display: flex; flex-wrap: wrap;">
        <% ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"].each do |time| %>
          <a href="<%=new_professional_appointment_path(professional)%>"
              class="btn btn-outline-primary m-1 <%= 'd-none' if @appointment_times.include?(time) || (Date.parse(date) == Date.today && time < Time.now.strftime('%H:%M')) %>"
              style="width: 22%;"
              data-time="<%= time %>"
              data-action="click->appointment-selected#confirm">
            <%= time %>
          </a>
        <%end%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_back.html.erb
<div class="d-flex flex-row align-items-center">
  <%= link_to :back, class:"text-decoration-none text-primary", style:"font-size: 16px" do%>
  <i class="fa-solid fa-chevron-left text-primary ms-4 me-3 mt-3"></i>Retour
  <% end %>
</div>

app/views/shared/_calendar.html.erb
<div class="m-4">
  <%= week_calendar(events: @appointments, professional: @professional) do |date, events| %>
    <div>
      <p data-appointment-target="date">
        <%= date.strftime("%d-%m-%Y") %>
      </p>
      <% events.each do |event| %>
        <p><%= event.user.first_name%> <%= event.user.last_name%></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fermer">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fermer">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start" style="sticky-bottom: 0;">
  <div class="container p-2">
    <div class="row d-flex justify-content-between">
      <div class="col-lg-8 col-md-7 col-sm-7 text-start">
        <%= image_tag  "https://res.cloudinary.com/dsbteudoz/image/upload/v1733824548/Boop_-_LOGO_FINAL_RVB_q1laee.png", style:"width: 20%;" %>
      </div>
      <div class="col-lg-4 col-sm-7 d-flex flex-row">
        <div>
          <ul class="list-unstyled mb-0 text-start">
           <h5 class="text-uppercase">Liens utiles</h5>
            <li>
              <%= link_to 'Accueil', root_path, class: 'text-dark' %>
            </li>
            <li>
              <%= link_to 'À propos', about_path, class: 'text-dark' %>
            </li>
            <li>
              <%= link_to 'Contact', contact_path, class: 'text-dark' %>
            </li>
            <li>
              <%= link_to 'Conditions générales', terms_path, class: 'text-dark' %>
            </li>
          </ul>
        </div>

        <div class=" ms-4">

              <h5 class="text-uppercase">Suivez-nous</h5>
                      <ul class="list-inline footer-links">
                          <li class="list-inline-item">
                              <a href="https://www.instagram.com/boop_officiel/" target="_blank">
                                  <i class="fab fa-instagram"></i>
                              </a>
                          </li>

                          <li class="list-inline-item">
                              <a href="https://www.tiktok.com/@boop_officiel?_t=8s9jTobM5eo&_r=1" target="_blank">
                                  <i class="fab fa-tiktok"></i>
                              </a>
                          </li>

                          <%# <li class="list-inline-item">
                              <a href="#">
                                  <i class="fab fa-facebook"></i>
                              </a>
                          </li>

                          <li class="list-inline-item">
                              <a href="#">
                                  <i class="fab fa-twitter"></i>
                              </a>
                          </li> %>

                      </ul>
                  </div>
              </div>


        </div>
      </div>
    </div>
  </div>



  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2024 Boop. Tous droits réservés.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand mx-4" do %>
      <%= image_tag "https://res.cloudinary.com/dsbteudoz/image/upload/v1733824548/Boop_-_LOGO_FINAL_BLANC_qgyjvj.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link text-white", style:"font-size: 20px" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Proposer un service", new_professional_path, class: "nav-link text-white mx-4", style:"font-size: 20px" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact", terms_path, class: "nav-link text-white", style:"font-size: 20px" %>
          </li>
          <li class="nav-item active">
            <%= link_to "A propos", about_path, class: "nav-link text-white mx-4", style:"font-size: 20px" %>
          </li>
          <li class="nav-item dropdown d-flex align-items-end flex-column">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu", style: "object-fit: cover" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" style="width: fit-content;" aria-labelledby="navbarDropdown">
              <%= link_to "Mes services", pro_index_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item btn btn-primary rounded rounded-4">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>