config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'à propos', to: 'pages#about', as: 'about'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'terms', to: 'pages#terms', as: 'terms'
    # autres routes...

  # Defines the root path route ("/")
  # root "posts#index"

  resources :professionals do
    resources :appointments, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
  end


  resources :users, only: [:show, :edit, :destroy] do
    member do
      get 'professionals', to: 'professionals#pro_index', as: :pro_index
      get 'professionals/:professional_id', to: 'professionals#pro_show', as: :pro_show
    end

    member do
      resources :pets
    end
  end

  resources :animals, only: [:index, :show]

  resources :pricings, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end


end

app/views/pages/about.html.erb
<div>
  <%= render "shared/back"%>
</div>
<div class="container">

  <h1 class="text-center my-4">À propos</h1>
  <div class="row">
    <div class="form-devise col-md-12">


      <p>
        Bienvenue sur notre page À propos. Ici, vous pouvez trouver des informations sur nos politiques et notre mission.
      </p>
      <h2>Notre Mission</h2>
      <p>
        Notre mission est de connecter les refuges, les familles et les experts pour des adoptions réussies. Nous croyons en l'importance de trouver des foyers aimants pour chaque animal.
      </p>
      <h2>Politiques</h2>
      <p>
        Nous nous engageons à respecter les normes les plus élevées en matière de bien-être animal. Nos politiques sont conçues pour assurer la sécurité et le bonheur de chaque animal adopté.
      </p>
      <h2>Politique de confidentialité</h2>
      <p>
        Nous respectons votre vie privée et nous nous engageons à protéger vos informations personnelles. Pour en savoir plus, veuillez consulter notre <%= link_to 'Politique de confidentialité', privacy_policy_path %>.
      </p>
      <h2>Conditions générales</h2>
      <p>
        En utilisant notre site, vous acceptez nos <%= link_to 'Conditions générales', terms_path %>. Veuillez les lire attentivement.
      </p>


    </div>
  </div>

app/views/pages/contact.html.erb
<div>
  <%= render "shared/back"%>
</div>
<div class="container">
  <h1 class="text-center my-4">Contactez-nous</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= form_with url: contact_path, method: :post, local: true do |form| %>
        <div class="mb-3">
          <%= form.label :name, "Nom", class: "form-label" %>
          <%= form.text_field :name, class: "form-control", required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :email, "Email", class: "form-label" %>
          <%= form.email_field :email, class: "form-control", required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :message, "Message", class: "form-label" %>
          <%= form.text_area :message, class: "form-control", rows: 5, required: true %>
        </div>
        <div class="text-center">
          <%= form.submit "Envoyer", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-all">
  <div class="banner">
    <div class="container text-end">
      <h1>Adopter avec amour,</h1>
      <h1>accompagner avec soin.</h1>
      <%= link_to animals_path, class: "btn btn-primary btn-spa text-white p-3 mt-4 text-end shadow", style:"border-radius: 32px;" do%>
        <span class="icon-custom">🐾</span> Je veux adopter !
      <%end%>
    </div>
  </div>
  <%= simple_form_for :search, url: professionals_path, method: :get do |f| %>
    <div class="d-flex justify-content-center search-form-control form-group mb-3", style="width: 100%;" >
      <div class="d-flex align-items-center search-form-control form-group w-form">
        <%= text_field_tag :query,
              params[:query],
              class: "form-control search-bar bg-secondary ps-5",
              placeholder: "Rechercher un service..."
          %>
        <div>
          <%= submit_tag "Rechercher", class: "btn btn-primary text-white search-bar p-3" %>
        </div>
      </div>
    </div>
  <% end %>

  <%# Service categories %>
  <h3 class="mt-5">Nos services</h3>
  <div class="d-flex justify-content-start custom-scroll mt-2", style="white-space: nowrap; overflow-x: auto;">
    <a href="<%=professionals_path%>"  style="text-decoration:none; color: white;">
      <div class="card-category p-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dsbteudoz/image/upload/v1734016805/vitaly-gariev-HURf5iUtSQg-unsplash_haxcr5.jpg);">
        <h4>Tous nos services</h4>
      </div>
    </a>
    <% (0...@all_specialty.length).each do |i| %>
      <% specialty = @all_specialty[i][:specialty]%>
      <% photo = @all_specialty[i][:photo]%>
      <% if @available_specialty.include?(specialty)%>
        <a href="<%=professionals_path(specialty: specialty)%>" style="text-decoration:none; color: white;">
          <div class="card-category p-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=photo%>);">
            <h4><%=specialty%></h4>
          </div>
        </a>
      <% else %>
        <a href="#" style="text-decoration:none; color: white; pointer-events: none;">
          <div class="card-category p-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=photo%>);">
            <div class="d-inline text-center" >
              <h4><%=specialty%></h4>
              <p>Bientôt disponible</p>
            </div>
          </div>
        </a>
      <% end %>
    <% end %>
  </div>

  <%# Add a service %>
  <h3 class="mt-5 text-center">Vous aussi, vous souhaitez proposer un service ?</h3>
  <div class="row d-flex justify-content-center align-items-center mt-4">
    <div class="col-12 col-lg-5 text-center pe-5">
      <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734608983/guy-walking-with-dog-in-the-park_ltkcew.png" alt="Proposer un service">
    </div>
    <div class="col-12 col-lg-5" style="word-wrap: break-word; word-break: break-word; white-space: normal; text-align: justify;">
      <h5>Vous adorez les animaux et vous avez des compétences à partager ?</h5>
      <br>
      <h5>Que vous soyez vétérinaire, comportementaliste, nutritionniste ou pet-sitter, Boop est fait pour vous ! </h5>
      <br>
      <h5>Rejoignez notre communauté et proposez vos services à des propriétaires d'animaux qui cherchent des solutions fiables et de confiance.</h5>

      <h5>C’est simple, rapide, et vous pouvez faire une vraie différence dans la vie des animaux tout en développant votre activité. Inscrivez-vous maintenant et commencez à aider nos compagnons à quatre pattes !
      </h5>
      <div class="text-center">
        <%= link_to "Proposer un service", new_professional_path, class: "btn btn-primary text-white mt-4 rounded-pill"%>
      </div>

    </div>

  </div>

  <%# appointments to come %>
  <h3 class="mt-5 mb-4">Vos futurs rendez-vous</h3>
  <% if user_signed_in? %>
    <% if @appointments.exists? %>
      <% @appointments.each do |appointment| %>
        <a href="<%=professional_appointment_path(appointment.professional, appointment)%>" style="color: black; text-decoration: none;">
          <div class="d-flex justify-content-center">
            <div class="card mt-1 mb-4 shadow card-appointment" >
              <div class="card-header bg-primary rounded-bottom shadow-sm">
                <div class="d-flex justify-content-around fw-bold">
                  <div class="d-flex align-items-center">
                    <i class="fa-regular fa-calendar-days"></i>
                    <p class="ms-3"><%= appointment.date.strftime("%d/%m/%Y") %></p>
                  </div>
                  <div class="d-flex align-items-center">
                    <i class="fa-regular fa-clock ms-5"></i>
                    <p class="ms-3"><%= appointment.start_time.strftime("%H:%M") %></p>
                  </div>
                </div>
              </div>
              <div class="card-body d-flex justify-content-center align-items-center">
                <%= image_tag url_for(appointment.professional.photo), alt:"Photo du professionnel", class:"small-rounded-circle"%>
                <div class="d-flex flex-column ms-4">
                  <p>
                    Rendez-vous avec : <%= appointment.professional.name%>
                  </p>
                  <p>
                    Lieu : <%= appointment.professional.address%>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    <% else %>
      <div class="d-flex justify-content-center align-items-center">
        <div class="d-flex flex-column justify-content-center align-items-center", style="width: 50%;">
          <p class="text-center">Vous n'avez pas de rendez-vous à venir.</p>
          <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1733845850/owner-playing-with-pet-dog_vfnehl.png">
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="d-flex justify-content-center align-items-center">
      <div class="d-flex flex-column justify-content-center align-items-center", style="width: 50%;">
        <p class="text-center">Veuillez vous connecter pour voir vos rendez-vous.</p>
        <%= link_to "Se connecter", new_user_session_path, class: "text-center btn btn-primary text-white"%>
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734099737/business-solution-removebg-preview_c0hr67.png">
      </div>
    </div>
  <% end %>
</div>

app/views/pages/privacy_policy.html.erb
<div>
  <%= render "shared/back"%>
</div>
<div class="container">
  <h1 class="text-center my-4">Politique de confidentialité</h1>
  <div class="row">
    <div class="form-devise">
      <p>
        Nous respectons votre vie privée et nous nous engageons à protéger vos informations personnelles. Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons vos informations.
      </p>

      <h2>Collecte des informations</h2>
      <p>
        Nous collectons des informations lorsque vous vous inscrivez sur notre site, passez une commande, vous abonnez à notre newsletter ou remplissez un formulaire. Les informations collectées incluent votre nom, votre adresse e-mail, votre numéro de téléphone et/ou votre carte de crédit.
      </p>
      <h2>Utilisation des informations</h2>
      <p>
        Toute information que nous collectons auprès de vous peut être utilisée pour :
        <ul>
          <li>Personnaliser votre expérience et répondre à vos besoins individuels</li>
          <li>Fournir un contenu publicitaire personnalisé</li>
          <li>Améliorer notre site web</li>
          <li>Améliorer le service client et vos besoins de prise en charge</li>
          <li>Vous contacter par e-mail</li>
          <li>Administrer un concours, une promotion, ou une enquête</li>
        </ul>
      </p>
      <h2>Protection des informations</h2>
      <p>
        Nous mettons en œuvre une variété de mesures de sécurité pour préserver la sécurité de vos informations personnelles. Nous utilisons un cryptage à la pointe de la technologie pour protéger les informations sensibles transmises en ligne. Nous protégeons également vos informations hors ligne. Seuls les employés qui ont besoin d'effectuer un travail spécifique (par exemple, la facturation ou le service client) ont accès aux informations personnelles identifiables. Les ordinateurs et serveurs utilisés pour stocker des informations personnelles identifiables sont conservés dans un environnement sécurisé.
      </p>
      <h2>Consentement</h2>
      <p>
        En utilisant notre site, vous consentez à notre politique de confidentialité.
      </p>
    </div>
  </div>
</div>

app/views/pages/terms.html.erb
<div>
  <%= render "shared/back"%>
</div>
<div class="container">
    <h1 class="text-center my-4">Conditions générales</h1>
  <div class="row">
    <div class="form-devise">


      <h2>Introduction</h2>
      <p>
        Bienvenue sur notre site. En utilisant notre site, vous acceptez les présentes conditions générales. Veuillez les lire attentivement.
      </p>
      <h2>Utilisation du site</h2>
      <p>
        Vous acceptez d'utiliser notre site uniquement à des fins légales et de manière à ne pas enfreindre les droits de, restreindre ou empêcher l'utilisation et la jouissance de ce site par un tiers.
      </p>
      <h2>Propriété intellectuelle</h2>
      <p>
        Tout le contenu présent sur ce site, y compris les textes, graphiques, logos, icônes, images, clips audio, téléchargements numériques et compilations de données, est la propriété de notre entreprise ou de ses fournisseurs de contenu et est protégé par les lois internationales sur le droit d'auteur.
      </p>
      <h2>Limitation de responsabilité</h2>
      <p>
        Nous ne serons pas responsables des dommages directs, indirects, accessoires, consécutifs ou punitifs découlant de votre utilisation de ce site.
      </p>
      <h2>Modifications des conditions générales</h2>
      <p>
        Nous nous réservons le droit de modifier ces conditions générales à tout moment. Les modifications prendront effet dès leur publication sur le site.
      </p>
      <h2>Contact</h2>
      <p>
        Si vous avez des questions concernant ces conditions générales, veuillez nous contacter à l'adresse suivante : <a href="mailto:chanlika.servais@gmail.com">Envoyer un email</a>.
      </p>
    </div>
  </div>
</div>