config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'à propos', to: 'pages#about', as: 'about'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'terms', to: 'pages#terms', as: 'terms'
    # autres routes...

  # Defines the root path route ("/")
  # root "posts#index"

  resources :professionals do
    resources :appointments, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
  end


  resources :users, only: [:show, :edit, :destroy] do
    member do
      get 'professionals', to: 'professionals#pro_index', as: :pro_index
      get 'professionals/:professional_id', to: 'professionals#pro_show', as: :pro_show
    end

    member do
      resources :pets
    end
  end

  resources :animals, only: [:index, :show]

  resources :pricings, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end


end

app/models/animal.rb
class Animal < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [ :shelter ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @animals = Animal.all
    if params[:query].present?
      @animals = Animal.search_by_city(params[:query])
      # sql_subquery = "name ILIKE :query OR species ILIKE :query"
      # @animals = @animals.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @animal = Animal.find(params[:id])
  end

end

app/views/animals/index.html.erb
<div>
  <%= render "shared/back"%>
</div>

<div class="container">
  <div id="carouselExampleSlidesOnly" class="carousel slide rounded-5" data-bs-ride="carousel" style="width: 100%; max-height: 71vh; overflow: hidden;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734621854/Design_sans_titre_taz0br.jpg" class="d-block w-100" alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734621854/Design_sans_titre_1_sryfuj.jpg" class="d-block w-100" alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734622498/Design_sans_titre_5_hzjvgu.jpg" class="d-block w-100" alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734622497/Design_sans_titre_6_kojqpk.jpg" class="d-block w-100 " alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734622497/Design_sans_titre_4_nyrr0m.jpg" class="d-block w-100 " alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734622493/Design_sans_titre_3_y01tpz.jpg" class="d-block w-100 " alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dsbteudoz/image/upload/v1734622491/Design_sans_titre_2_yat5du.jpg" class="d-block w-100 " alt="Photo d'animaux heureux" style="transition: 3s ease">
      </div>
    </div>
  </div>

  <h1 class="text-center my-4">🐾 Ils cherchent une nouvelle famille 🏠</h1>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: animals_path, method: :get, class: "d-flex" do %>


      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Rechercher par ville"
        %>
      <%= submit_tag "Recherche", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


  <div class="d-flex flex-wrap justify-content-center" data-controller="animal-index">
    <% @animals.each do |animal| %>
      <a  href="<%=animal_path(animal)%>"
          style="text-decoration: none; color: black; margin: 20px">
        <div class="col">
          <div  class="m-2 card_pro p-0 d-flex flex-column"
                style="width: 300px; aspect-ratio: 1/1; overflow: hidden;"
                data-animal-index-target="animal"
                data-action="mouseover->animal-index#hover mouseout->animal-index#unhover">
            <!-- En-tête -->
            <div class="p-3 text-center" style="border-radius: 8px 8px 0 0; background-color: #f7e6d4;">
              <%=animal.name %>
            </div>
            <!-- Image qui prend le reste de la place -->
            <div class="flex-grow-1" style="overflow: hidden;">
              <%= image_tag animal.photo, style: "width: 100%; height: 100%; object-fit: cover;" %>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/animals/show.html.erb
<div>
  <%= render "shared/back"%>
</div>
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-5 col-sm-10 card_pro">
      <%= image_tag @animal.photo, class: "card-img-top w-100 h-100", style: "object-fit: cover" if @animal.photo.present? %>
    </div>
    <div class="col-lg-5 col-sm-10 card_pro d-flex flex-column justify-content-between">
      <div>
        <h3 class="text-center m-3"><strong><%= @animal.name %></strong></h3>
        <p class="my-2">Âge: <%= @animal.age %></p>
        <p>Sexe: <%= @animal.sex %></p>
        <p class="my-2">Race: <%= @animal.species %></p>
        <p>Description: <%= @animal.description %></p>
        <p class="my-2">Refuge: <%=@animal.shelter%></p>
      </div>
      <div>
        <p style="font-size: 36px"> <i class="fa-solid fa-paw float-end text-primary"></i></p>
      </div>
    </div>
  </div>
</div>